### ISSUE TITLE
클래스 다이어그램 수정

### ISSUE THREAD

**Issue by wsehyeon** [wsehyeon/ft_irc#4]
변경된 구조에 맞도록 수정

**Comment by ilp-sys** [comment]
server의 getInstance가 const인게 맞는지 궁금해요

**Comment by wsehyeon** [comment]
> server의 getInstance가 const인게 맞는지 궁금해요
get...() 메소드들에 const & 를 복붙하다가 일어난 사태입니다.
3/11일 기준 결정된 내용으로 클래스 다이어그램을 수정해두겠습니다

OCCF 함수들은 클래스 다이어그램에서 제외하고자 하는데 어떻게 생각하시나요

**Comment by ilp-sys** [comment]
OCCF함수 생략 동의합니다
